server:
  port: 8080
spring:
  application:
    name: gateway-service
# FIXME: Investigate why bean is conflicting
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/product/**
#          filters:
#            - RewritePath=/product(?<segment>.*), $\{segment}


